services:
  # O Backend (Node.js API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erpfacilita-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      # Esse volume é crucial: ele garante que o SQLite salvo no dev.db permaneça
      # mesmo se o container reiniciar ou atualizar
      - prisma_data:/app/prisma/
    environment:
      - DATABASE_URL=file:./dev.db
    # O Frontend (React via Nginx)
    # O Frontend (React via Nginx)
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        # Repare que agora a API dele usa HTTPS tbm!
        - VITE_API_URL=https://facilita3d.shop:3001
    container_name: erpfacilita-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Abrimos a porta Mágica do HTTPS (Cadeado)
    volumes:
      # Esse volume pega o cadeado gerado na AWS e injeta lá nos ouvidos do Nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

volumes:
  # Declaração do volume persistente de banco de dados SQLite
  prisma_data:
