server {
    listen 80;
    server_name facilita3d.shop www.facilita3d.shop;

    # Opcional (Redirecionar todo mundo que entra sem cadeado direto pro cadeado)
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name facilita3d.shop www.facilita3d.shop;

    # Aqui é o segredo: Onde "injetamos" o cadeado que a AWS girou!
    ssl_certificate /etc/letsencrypt/live/facilita3d.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/facilita3d.shop/privkey.pem;
    
    # Configurações de segurança recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
