server {
    listen 80;
    
    # Pasta raiz onde estão os arquivos estáticos do React
    root /usr/share/nginx/html;
    index index.html index.htm;

    # O React-Router exige que qualquer URL não encontrada retorne o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
